# Generated by Django 4.0.9 on 2023-02-26 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_purchasedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
